### ISSUE TITLE
Unable to access wallet with hugnet

### ISSUE THREAD

**Issue by kmw101** [iov-one/wallet-demo#297]
> I tried to log in into the wallet, wallet.hugnet.iov.one. I signed up but somehow never got in the wallet. I tried again but somehow the password is wrong, so i click reset: I am being asked my 12 words which I never got since I never got in. So I am trying to signup with a different address for testing, but when i try to go to the signup url, it keeps redirecting me to the login url and I cannot sign up with another email address. I am trying on Firefox. I tried the same on Chrome, the signup did not go to any page and staid on the signup page, and then i got the same problems as on Firefox.> 

Unable to access wallet:
1) Missing recovery phrase - no recovery reset possible. QUESTION - do we give the user the ability to clear the wallet and start with a clean login? Given this is a demo wallet it might be nice to have a hard reset?

**Comment by webmaster128** [comment]
Closing since this is marked as done
